spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAM}
    password: ${PROD_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always